├── App.tsx  -- one error ├── layout │   ├── MainLayout │   │   ├── Header │   │   │   ├── Customization │   │   │   │   └── index.tsx ->  1 error Type 'Element' is not assignable to type 'string'. │   │   └── Sidebar │   │       └── MenuList │   │           ├── NavCollapse │   │           │   └── index.tsx -> 2 error TS2604: JSX element type 'Icon' does not have any construct or call signatures. │   │           └── NavItem │   │               └── index.tsx -> 2 error TS2604: JSX element type 'Icon' does not have any construct or call signatures. └── views     └── utilities         ├── color         │   └── index.tsx ->  1 error Type 'Element' is not assignable to type 'string'.         ├── shadow         │   └── index.tsx ->  1 error Type 'Element' is not assignable to type 'string'.         └── typography             └── index.tsx ->  1 error Type 'Element' is not assignable to type 'string'.
run this command to ignore errors:
TSC_COMPILE_ON_ERROR=true yarn start